{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "renewal-desk.fullname" . }}-ui
  labels:
    {{- include "renewal-desk.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "renewal-desk.name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "renewal-desk.name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
      annotations:
        checksum/ui-config: {{ include (print $.Template.BasePath "/ui-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ui-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: ui-content
          configMap:
            name: {{ include "renewal-desk.fullname" . }}-ui
{{- end }}
