{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "renewal-desk.fullname" . }}-ui
  labels:
    {{- include "renewal-desk.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "renewal-desk.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      {{- if eq .Values.ui.service.type "NodePort" }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
{{- end }}
